module Dicionario where

import Data.Map (Map)
import qualified Data.Map as Map

-- Tipos para o dicionário e a língua
type Dictionary = Map String String
data Language = English | Spanish | French | Portuguese | Unknown deriving (Show, Eq)

-- Dicionários para cada língua
englishDict, spanishDict, frenchDict :: Dictionary

-- Dicionário de inglês para português
englishDict = Map.fromList [
  ("i", "eu"), ("you", "você"), ("he", "ele"), ("she", "ela"), ("it", "isso"), ("we", "nós"), ("they", "eles")
 , ("my", "meu"), ("your", "seu"), ("his", "dele"), ("her", "dela"), ("its", "seu"), ("our", "nosso"), ("their", "deles")
 , ("this", "este"), ("that", "aquele"), ("these", "estes"), ("those", "aqueles"),
 ("walk", "andar"), ("walks", "anda"), ("walked", "andou"), ("walking", "andando"),
 ("run", "correr"), ("runs", "corre"), ("ran", "correu"), ("running", "correndo"),
 ("eat", "comer"), ("eats", "come"), ("ate", "comeu"), ("eating", "comendo"),
 ("read", "ler"), ("reads", "lê"), ("read", "leu"), ("reading", "lendo"),
 ("write", "escrever"), ("writes", "escreve"), ("wrote", "escreveu"), ("writing", "escrevendo"),
 ("hello", "olá"), ("world", "mundo"), ("how", "como"), ("are", "está"), ("you", "você"),
 ("goodbye", "adeus"), ("please", "por favor"), ("thank", "obrigado"), ("sorry", "desculpe"),
 ("friend", "amigo"), ("family", "família"), ("love", "amor"), ("food", "comida"), ("water", "água"),
 ("house", "casa"), ("car", "carro"), ("book", "livro"), ("school", "escola"), ("work", "trabalho"),
 ("happy", "feliz"), ("sad", "triste"), ("big", "grande"), ("small", "pequeno"), ("old", "velho"),
 ("new", "novo"), ("hot", "quente"), ("cold", "frio"), ("fast", "rápido"), ("slow", "lento"),
 ("right", "certo"), ("left", "esquerdo"), ("up", "cima"), ("down", "baixo"), ("here", "aqui"),
 ("there", "lá"), ("yes", "sim"), ("no", "não"), ("maybe", "talvez"), ("never", "nunca"),
 ("always", "sempre"), ("sometimes", "às vezes"), ("often", "frequentemente"), ("seldom", "raramente"),
 ("today", "hoje"), ("tomorrow", "amanhã"), ("yesterday", "ontem"), ("morning", "manhã"),
 ("afternoon", "tarde"), ("evening", "noite"), ("night", "noite"), ("time", "tempo"),
 ("day", "dia"), ("week", "semana"), ("month", "mês"), ("year", "ano"), ("school", "escola"),
 ("teacher", "professor"), ("student", "aluno"), ("class", "aula"), ("subject", "disciplina"),
 ("test", "teste"), ("exam", "exame"), ("homework", "dever de casa"), ("play", "brincar"),
 ("game", "jogo"), ("music", "música"), ("dance", "dançar"), ("art", "arte"), ("science", "ciência"),
 ("math", "matemática"), ("history", "história"), ("geography", "geografia"), ("language", "língua"),
 ("computer", "computador"), ("internet", "internet"), ("phone", "telefone"), ("message", "mensagem"),
 ("call", "chamada"), ("chat", "conversar"), ("talk", "falar"), ("listen", "ouvir"),
 ("speak", "falar"), ("read", "ler"), ("write", "escrever"), ("draw", "desenhar"),
 ("paint", "pintar"), ("cook", "cozinhar"), ("eat", "comer"), ("drink", "beber"), ("sleep", "dormir"),
 ("wake", "acordar"),  ("jump", "saltar"), ("swim", "nadar"),
 ("play", "brincar"), ("sing", "cantar"), ("laugh", "rir"), ("cry", "chorar"), ("smile", "sorrir"),
 ("think", "pensar"), ("believe", "acreditar"), ("know", "saber"), ("understand", "entender"),
 ("remember", "lembrar"), ("forget", "esquecer"), ("try", "tentar"), ("help", "ajudar"),
 ("love", "amar"), ("hate", "odiar"), ("like", "gostar"), ("dislike", "não gostar"),
 ("want", "querer"), ("need", "precisar"), ("have", "ter"), ("be", "ser"), ("do", "fazer"),
 ("go", "ir"), ("come", "vir"), ("see", "ver"), ("look", "olhar"), ("give", "dar"),
 ("take", "pegar"), ("show", "mostrar"), ("tell", "contar"), ("ask", "perguntar"),
 ("answer", "responder"), ("call", "chamar"), ("meet", "encontrar"), ("find", "encontrar"),
 ("lose", "perder"), ("win", "ganhar"), ("fight", "lutar"), ("argue", "discutir"),
 ("agree", "concordar"), ("disagree", "discordar"), ("decide", "decidir"), ("choose", "escolher"),
 ("plan", "planejar"), ("prepare", "preparar"), ("wait", "esperar"), ("believe", "acreditar"),
 ("wish", "desejar"), ("hope", "esperar"), ("pray", "orar"), ("dream", "sonhar"),
 ("travel", "viajar"), ("explore", "explorar"), ("visit", "visitar"), ("discover", "descobrir"),
 ("remember", "lembrar"), ("forget", "esquecer"), ("create", "criar"), ("build", "construir"),
 ("make", "fazer"), ("fix", "consertar"), ("break", "quebrar"), ("repair", "reparar"),
 ("improve", "melhorar"), ("change", "mudar"), ("grow", "crescer"), ("learn", "aprender"),
 ("teach", "ensinar"), ("study", "estudar"), ("practice", "praticar"), ("try", "tentar"),
 ("play", "jogar"), ("enjoy", "aproveitar"), ("like", "gostar"), ("love", "amar"),
 ("hate", "odiar"), ("prefer", "preferir"), ("choose", "escolher"), ("decide", "decidir"),
 ("want", "querer"), ("need", "precisar"), ("have", "ter"), ("give", "dar"),
 ("get", "receber"), ("take", "pegar"), ("buy", "comprar"), ("sell", "vender"),
 ("ask", "perguntar"), ("answer", "responder"), ("tell", "contar"), ("say", "dizer"),
 ("call", "chamar"), ("speak", "falar"), ("talk", "conversar"), ("discuss", "discutir"),
 ("argue", "discutir"), ("agree", "concordar"), ("disagree", "discordar"), ("complain", "reclamar"),
 ("apologize", "pedir desculpas"), ("thank", "agradecer"), ("invite", "convidar"),
 ("accept", "aceitar"), ("refuse", "recusar"), ("support", "apoiar"), ("help", "ajudar"),
 ("assist", "assistir"), ("encourage", "encorajar"), ("motivate", "motivar"), ("advise", "aconselhar"),
 ("recommend", "recomendar"), ("suggest", "sugerir"), ("predict", "prever"), ("hope", "esperar"),
 ("wish", "desejar"), ("fear", "temer"), ("worry", "preocupar"), ("doubt", "duvidar"),
 ("believe", "acreditar"), ("trust", "confiar"), ("love", "amar"), ("hate", "odiar"),
 ("like", "gostar"), ("dislike", "não gostar"), ("enjoy", "aproveitar"), ("prefer", "preferir"),
 ("respect", "respeitar"), ("value", "valorizar"), ("appreciate", "apreciar"), ("admire", "admirar"),
 ("criticize", "criticar"), ("judge", "julgar"), ("blame", "culpar"), ("forgive", "perdoar"),
 ("accept", "aceitar"), ("reject", "rejeitar"), ("tolerate", "tolerar"), ("understand", "entender"),
 ("know", "saber"), ("learn", "aprender"), ("teach", "ensinar"), ("show", "mostrar"),
 ("tell", "contar"), ("explain", "explicar"), ("describe", "descrever"), ("discuss", "discutir"),
 ("argue", "discutir"), ("debate", "debater"), ("negociate", "negociar"), ("compromise", "comprometer"),
 ("persuade", "persuadir"), ("convince", "convencer"), ("motivate", "motivar"), ("inspire", "inspirar"),
 ("encourage", "encorajar"), ("entertain", "entreter"), ("amuse", "divertir"), ("delight", "encantar"),
 ("surprise", "surpreender"), ("fascinate", "fascinar"), ("impress", "impressionar"),
 ("influence", "influenciar"), ("affect", "afetar"), ("change", "mudar"), ("transform", "transformar"),
 ("improve", "melhorar"), ("enhance", "aumentar"), ("develop", "desenvolver"), ("grow", "crescer"),
 ("progress", "progredir"), ("advance", "avançar"), ("move", "mover"), ("relocate", "realocar"),
 ("travel", "viajar"), ("explore", "explorar"), ("discover", "descobrir"), ("experience", "experienciar"),
 ("enjoy", "aproveitar"), ("savor", "saborear"), ("taste", "provar"), ("smell", "cheirar"),
 ("hear", "ouvir"), ("see", "ver"), ("feel", "sentir"), ("touch", "tocar"), ("think", "pensar"),
 ("believe", "acreditar"), ("imagine", "imaginar"), ("dream", "sonhar"), ("create", "criar"),
 ("invent", "inventar"), ("design", "desenhar"), ("develop", "desenvolver"), ("produce", "produzir"),
 ("make", "fazer"), ("build", "construir"), ("construct", "construir"), ("assemble", "montar"),
 ("manufacture", "manufacturar"), ("fabricate", "fabricar"), ("repair", "consertar"), ("fix", "consertar"),
 ("maintain", "manter"), ("upgrade", "atualizar"), ("improve", "melhorar"), ("enhance", "aumentar"),
 ("alter", "alterar"), ("change", "mudar"), ("modify", "modificar"), ("adapt", "adaptar"),
 ("customize", "personalizar"), ("tailor", "ajustar"), ("reshape", "reformar"), ("reshape", "reformar"),
 ("reorganize", "reorganizar"), ("restructure", "reestruturar"), ("remodel", "remodelar"),
 ("revise", "rever"), ("edit", "editar"), ("proofread", "revisar"), ("polish", "polir"),
 ("refine", "refinar"), ("clarify", "esclarecer"), ("simplify", "simplificar"), ("summarize", "resumir"),
 ("condense", "condensar"), ("distill", "destilar"), ("eliminate", "eliminar"), ("remove", "remover"),
 ("cut", "cortar"), ("slice", "fatiar"), ("dice", "cortar em cubos"), ("chop", "picotar"),
 ("grate", "ralar"), ("mix", "misturar"), ("stir", "mexer"), ("blend", "misturar"), ("whisk", "bater"),
 ("knead", "sovar"), ("roll", "enrolar"), ("bake", "assar"), ("cook", "cozinhar"), ("fry", "fritar"),
 ("boil", "ferver"), ("steam", "cozinhar a vapor"), ("roast", "assar"), ("grill", "grelhar"),
 ("barbecue", "churrasco"), ("toast", "tostar"), ("season", "temperar"), ("spice", "especiarias"),
 ("sauté", "refogar"), ("braise", "cozinhar lentamente"), ("cure", "curar"), ("pickle", "conservar"),
 ("ferment", "fermentar"), ("smoke", "defumar"), ("dry", "secar"), ("freeze", "congelar"),
 ("preserve", "preservar"), ("pickle", "conservar"), ("can", "enlatado"), ("jar", "potes"),
 ("bottle", "garrafa"), ("package", "embalar"), ("wrap", "embrulhar"), ("seal", "selar"),
 ("label", "etiquetar"), ("store", "armazenar"), ("organize", "organizar"), ("arrange", "arranjar"),
 ("sort", "classificar"), ("categorize", "categorizar"), ("file", "arquivar"), ("archive", "arquivar"),
 ("keep", "manter"), ("hold", "segurar"), ("safeguard", "salvaguardar"), ("protect", "proteger"),
 ("preserve", "preservar"), ("defend", "defender"), ("shield", "escudo"), ("secure", "garantir"),
 ("lock", "trancar"), ("unlock", "destrancar"), ("barricade", "barricada"), ("fortify", "fortalecer"),
 ("reinforce", "reforçar"), ("strengthen", "fortalecer"), ("support", "apoiar"), ("assist", "ajudar"),
 ("guide", "guiar"), ("lead", "liderar"), ("navigate", "navegar"), ("direct", "direcionar"),
 ("manage", "gerenciar"), ("oversee", "supervisionar"), ("supervise", "supervisionar"), ("coordinate", "coordenar"),
 ("facilitate", "facilitar"), ("organize", "organizar"), ("prepare", "preparar"), ("plan", "planejar"),
 ("strategize", "estrategizar"), ("execute", "executar"), ("implement", "implementar"), ("carry out", "realizar"),
 ("perform", "executar"), ("conduct", "conduzir"), ("run", "executar"), ("operate", "operar"),
 ("function", "funcionar"), ("execute", "executar"), ("fulfill", "cumprir"), ("accomplish", "realizar"),
 ("achieve", "alcançar"), ("attain", "alcançar"), ("reach", "atingir"), ("obtain", "obter"),
 ("gain", "ganhar"), ("secure", "garantir"), ("acquire", "adquirir"), ("possess", "possuir"),
 ("own", "possuir"), ("have", "ter"), ("hold", "segurar"), ("retain", "reter"), ("keep", "manter"),
 ("store", "armazenar"), ("safeguard", "salvaguardar"), ("protect", "proteger"), ("preserve", "preservar"),
 ("save", "salvar"), ("conserve", "conservar"), ("safeguard", "salvaguardar"), ("maintain", "manter"),
 ("support", "apoiar"), ("sustain", "sustentar"), ("uphold", "sustentar"), ("advocate", "advogar"),
 ("promote", "promover"), ("encourage", "encorajar"), ("foster", "promover"), ("cultivate", "cultivar"),
 ("nurture", "nutrir"), ("raise", "levantar"), ("bring up", "criar"), ("educate", "educar"),
 ("inform", "informar"), ("enlighten", "esclarecer"), ("illuminate", "iluminar"), ("clarify", "esclarecer"),
 ("explain", "explicar"), ("demonstrate", "demonstrar"), ("show", "mostrar"), ("illustrate", "ilustrar"),
 ("depict", "representar"), ("portray", "retratar"), ("describe", "descrever"), ("narrate", "narrar"),
 ("recount", "recontar"), ("relate", "relatar"), ("tell", "contar"), ("share", "compartilhar"),
 ("spread", "espalhar"), ("disseminate", "disseminar"), ("broadcast", "transmitir"), ("publish", "publicar"),
 ("print", "imprimir"), ("release", "lançar"), ("launch", "lançar"), ("distribute", "distribuir"),
 ("circulate", "circular"), ("disperse", "dispersar"), ("scatter", "espalhar"), ("sprinkle", "polvilhar"),
 ("dust", "pó"), ("spread", "espalhar"), ("sow", "semear"), ("plant", "plantar"), ("grow", "crescer"),
 ("raise", "levantar"), ("cultivate", "cultivar"), ("harvest", "colher"), ("gather", "reunir"),
 ("collect", "coletar"), ("assemble", "montar"), ("organize", "organizar"), ("arrange", "arranjar"),
 ("sort", "classificar"), ("categorize", "categorizar"), ("file", "arquivar"), ("archive", "arquivar"),
 ("keep", "manter"), ("hold", "segurar"), ("safeguard", "salvaguardar"), ("protect", "proteger"),
 ("preserve", "preservar"), ("defend", "defender"), ("shield", "escudo"), ("secure", "garantir"),
 ("lock", "trancar"), ("unlock", "destrancar"), ("barricade", "barricada"), ("fortify", "fortalecer"),
 ("reinforce", "reforçar"), ("strengthen", "fortalecer"), ("support", "apoiar"), ("assist", "ajudar"),
 ("guide", "guiar"), ("lead", "liderar"), ("navigate", "navegar"), ("direct", "direcionar"),
 ("manage", "gerenciar"), ("oversee", "supervisionar"), ("supervise", "supervisionar"), ("coordinate", "coordenar"),
 ("facilitate", "facilitar"), ("organize", "organizar"), ("prepare", "preparar"), ("plan", "planejar"),
 ("strategize", "estrategizar"), ("execute", "executar"), ("implement", "implementar"), ("carry out", "realizar"),
 ("perform", "executar"), ("conduct", "conduzir"), ("run", "executar"), ("operate", "operar"),
 ("function", "funcionar"), ("execute", "executar"), ("fulfill", "cumprir"), ("accomplish", "realizar"),
 ("achieve", "alcançar"), ("attain", "alcançar"), ("reach", "atingir"), ("obtain", "obter"),
 ("gain", "ganhar"), ("secure", "garantir"), ("acquire", "adquirir"), ("possess", "possuir"),
 ("own", "possuir"), ("have", "ter"), ("hold", "segurar"), ("retain", "reter"), ("keep", "manter"),
 ("store", "armazenar"), ("safeguard", "salvaguardar"), ("protect", "proteger"), ("preserve", "preservar"),
 ("save", "salvar"), ("conserve", "conservar"), ("safeguard", "salvaguardar"), ("maintain", "manter"),
 ("support", "apoiar"), ("sustain", "sustentar"), ("uphold", "sustentar"), ("advocate", "advogar"),
 ("promote", "promover"), ("encourage", "encorajar"), ("foster", "promover"), ("cultivate", "cultivar"),
 ("nurture", "nutrir"), ("raise", "levantar"), ("bring up", "criar"), ("educate", "educar"),
 ("inform", "informar"), ("enlighten", "esclarecer"), ("illuminate", "iluminar"), ("clarify", "esclarecer"),
 ("explain", "explicar"), ("demonstrate", "demonstrar"), ("show", "mostrar"), ("illustrate", "ilustrar"),
 ("depict", "representar"), ("portray", "retratar"), ("describe", "descrever"), ("narrate", "narrar"),
 ("recount", "recontar"), ("relate", "relatar"), ("tell", "contar"), ("share", "compartilhar"),
 ("spread", "espalhar"), ("disseminate", "disseminar"), ("broadcast", "transmitir"), ("publish", "publicar"),
 ("print", "imprimir"), ("release", "lançar"), ("launch", "lançar"), ("distribute", "distribuir"),
 ("circulate", "circular"), ("disperse", "dispersar"), ("scatter", "espalhar"), ("sprinkle", "polvilhar"),
 ("dust", "pó"), ("spread", "espalhar"), ("sow", "semear"), ("plant", "plantar"), ("grow", "crescer"),
 ("raise", "levantar"), ("cultivate", "cultivar"), ("harvest", "colher"), ("gather", "reunir"),
 ("collect", "coletar"), ("assemble", "montar"), ("organize", "organizar"), ("arrange", "arranjar"),
 ("sort", "classificar"), ("categorize", "categorizar"), ("file", "arquivar"), ("archive", "arquivar"),
 ("keep", "manter"), ("hold", "segurar"), ("safeguard", "salvaguardar"), ("protect", "proteger"),
 ("preserve", "preservar"), ("defend", "defender"), ("shield", "escudo"), ("secure", "garantir"),
 ("lock", "trancar"), ("unlock", "destrancar"), ("barricade", "barricada"), ("fortify", "fortalecer"),
 ("reinforce", "reforçar"), ("strengthen", "fortalecer"), ("support", "apoiar"), ("assist", "ajudar"),
 ("guide", "guiar"), ("lead", "liderar"), ("navigate", "navegar"), ("direct", "direcionar"),
 ("manage", "gerenciar"), ("oversee", "supervisionar"), ("supervise", "supervisionar"), ("coordinate", "coordenar"),
 ("facilitate", "facilitar"), ("organize", "organizar"), ("prepare", "preparar"), ("plan", "planejar"),
 ("strategize", "estrategizar"), ("execute", "executar"), ("implement", "implementar"), ("carry out", "realizar"),
 ("perform", "executar"), ("conduct", "conduzir"), ("run", "executar"), ("operate", "operar"),
 ("function", "funcionar"), ("execute", "executar"), ("fulfill", "cumprir"), ("accomplish", "realizar"),
 ("achieve", "alcançar"), ("attain", "alcançar"), ("reach", "atingir"), ("obtain", "obter"),
 ("gain", "ganhar"), ("secure", "garantir"), ("acquire", "adquirir"), ("possess", "possuir"),
 ("own", "possuir"), ("have", "ter"), ("hold", "segurar"), ("retain", "reter"), ("keep", "manter"),
 ("store", "armazenar"), ("safeguard", "salvaguardar"), ("protect", "proteger"), ("preserve", "preservar"),
 ("save", "salvar"), ("conserve", "conservar"), ("safeguard", "salvaguardar"), ("maintain", "manter"),
 ("support", "apoiar"), ("sustain", "sustentar"), ("uphold", "sustentar"), ("advocate", "advogar"),
 ("promote", "promover"), ("encourage", "encorajar"), ("foster", "promover"), ("cultivate", "cultivar"),
 ("nurture", "nutrir"), ("raise", "levantar"), ("bring up", "criar"), ("educate", "educar"),
 ("inform", "informar"), ("enlighten", "esclarecer"), ("illuminate", "iluminar"), ("clarify", "esclarecer"),
 ("explain", "explicar"), ("demonstrate", "demonstrar"), ("show", "mostrar"), ("illustrate", "ilustrar"),
 ("depict", "representar"), ("portray", "retratar"), ("describe", "descrever"), ("narrate", "narrar"),
 ("recount", "recontar"), ("relate", "relatar"), ("tell", "contar"), ("share", "compartilhar"),
 ("spread", "espalhar"), ("disseminate", "disseminar"), ("broadcast", "transmitir"), ("publish", "publicar"),
 ("print", "imprimir"), ("release", "lançar"), ("launch", "lançar"), ("distribute", "distribuir"),
 ("circulate", "circular"), ("disperse", "dispersar"), ("scatter", "espalhar"), ("sprinkle", "polvilhar"),
 ("walk", "andar"), ("walks", "anda"), ("walked", "andou"), ("walking", "andando"),
 ("run", "correr"), ("runs", "corre"), ("ran", "correu"), ("running", "correndo"),
 ("eat", "comer"), ("eats", "come"), ("ate", "comeu"), ("eating", "comendo"),
 ("read", "ler"), ("reads", "lê"), ("read", "leu"), ("reading", "lendo"),
 ("write", "escrever"), ("writes", "escreve"), ("wrote", "escreveu"), ("writing", "escrevendo")
 ]

-- Dicionário de espanhol para português
spanishDict = Map.fromList [
 ("hola", "olá"),  ("yo", "eu"), ("tú", "você"), ("él", "ele"), ("ella", "ela"), ("eso", "isso"), ("nosotros", "nós"), ("ellos", "eles")
    , ("mi", "meu"), ("tu", "seu"), ("su", "dele"), ("su", "dela"), ("su", "seu"), ("nuestro", "nosso"), ("su", "deles")
    , ("este", "este"), ("ese", "aquele"), ("estos", "estes"), ("esos", "aqueles"),("mundo", "mundo"), ("cómo", "como"), ("estás", "está"), ("tú", "você"),
 ("adiós", "adeus"), ("por favor", "por favor"), ("gracias", "obrigado"), ("lo siento", "desculpe"),
 ("amigo", "amigo"), ("familia", "família"), ("amor", "amor"), ("comida", "comida"), ("agua", "água"),
 ("casa", "casa"), ("coche", "carro"), ("libro", "livro"), ("escuela", "escola"), ("trabajo", "trabalho"),
 ("feliz", "feliz"), ("triste", "triste"), ("grande", "grande"), ("pequeño", "pequeno"), ("viejo", "velho"),
 ("nuevo", "novo"), ("caliente", "quente"), ("frío", "frio"), ("rápido", "rápido"), ("lento", "lento"),
 ("derecha", "certo"), ("izquierda", "esquerdo"), ("arriba", "cima"), ("abajo", "baixo"),
 ("aquí", "aqui"), ("allí", "ali"), ("ayer", "ontem"), ("hoy", "hoje"), ("mañana", "amanhã"),
 ("tiempo", "tempo"), ("día", "dia"), ("noche", "noite"), ("sol", "sol"), ("luna", "lua"),
 ("estrella", "estrela"), ("mar", "mar"), ("tierra", "terra"), ("cielo", "céu"), ("viento", "vento"),
 ("fuego", "fogo"), ("agua", "água"), ("naturaleza", "natureza"), ("animal", "animal"),
 ("planta", "planta"), ("comer", "comer"), ("beber", "beber"), ("dormir", "dormir"),
 ("hablar", "falar"), ("escuchar", "ouvir"), ("ver", "ver"), ("sentir", "sentir"),
 ("tocar", "tocar"), ("jugar", "jogar"), ("correr", "correr"), ("caminar", "andar"),
 ("saltar", "pular"), ("bailar", "dançar"), ("cantar", "cantar"), ("reír", "rir"),
 ("llorar", "chorar"), ("trabajar", "trabalhar"), ("estudiar", "estudar"), ("viajar", "viajar"),
 ("conocer", "conhecer"), ("encontrar", "encontrar"), ("ver", "ver"), ("mostrar", "mostrar"),
 ("decir", "dizer"), ("hablar", "falar"), ("pensar", "pensar"), ("creer", "acreditar"),
 ("imaginar", "imaginar"), ("soñar", "sonhar"), ("crear", "criar"), ("diseñar", "desenhar"),
 ("hacer", "fazer"), ("construir", "construir"), ("fabricar", "fabricar"), ("producir", "produzir"),
 ("comprar", "comprar"), ("vender", "vender"), ("dar", "dar"), ("recibir", "receber"),
 ("regalar", "dar de presente"), ("usar", "usar"), ("llevar", "levar"), ("traer", "trazer"),
 ("enviar", "enviar"), ("recoger", "pegar"), ("pagar", "pagar"), ("cobrar", "cobrar"),
 ("ahorrar", "economizar"), ("gastar", "gastar"), ("invertir", "investir"), ("pedir", "pedir"),
 ("tomar", "tomar"), ("dar", "dar"), ("recoger", "pegar"), ("dejar", "deixar"),
 ("luchar", "lutar"), ("pelear", "brigar"), ("discutir", "discutir"), ("resolver", "resolver"),
 ("decidir", "decidir"), ("elegir", "escolher"), ("esperar", "esperar"), ("desear", "desejar"),
 ("buscar", "procurar"), ("encontrar", "encontrar"), ("perder", "perder"), ("ganar", "ganhar"),
 ("ayudar", "ajudar"), ("enseñar", "ensinar"), ("aprender", "aprender"), ("informar", "informar"),
 ("advertir", "avisar"), ("advertir", "avisar"), ("avisar", "avisar"), ("avisar", "avisar"),
 ("prometer", "prometer"), ("cumplir", "cumprir"), ("descubrir", "descobrir"), ("encontrar", "encontrar"),
 ("compartir", "compartilhar"), ("reunir", "reunir"), ("juntar", "juntar"), ("revisar", "rever"),
 ("verificar", "verificar"), ("analizar", "analisar"), ("estudiar", "estudar"), ("investigar", "investigar"),
 ("explorar", "explorar"), ("probar", "experimentar"), ("calibrar", "calibrar"), ("medir", "medir"),
 ("pesar", "pesar"), ("separar", "separar"), ("clasificar", "classificar"), ("etiquetar", "etiquetar"),
 ("organizar", "organizar"), ("preparar", "preparar"), ("guardar", "guardar"), ("archivar", "arquivar"),
 ("borrar", "deletar"), ("sacar", "tirar"), ("quitar", "remover"), ("colocar", "colocar"),
 ("despejar", "limpar"), ("limpiar", "limpar"), ("remover", "remover"), ("reemplazar", "substituir"),
 ("sustituir", "substituir"), ("actualizar", "atualizar"), ("refrescar", "atualizar"), ("renovar", "renovar"),
 ("cambiar", "trocar"), ("alterar", "alterar"), ("modificar", "modificar"), ("mejorar", "melhorar"),
 ("mejorar", "melhorar"), ("optimizar", "otimizar"), ("ajustar", "ajustar"), ("perfeccionar", "aperfeiçoar"),
 ("desarrollar", "desenvolver"), ("evolucionar", "evoluir"), ("crecer", "crescer"), ("expandir", "expandir"),
 ("aumentar", "aumentar"), ("ampliar", "ampliar"), ("incrementar", "aumentar"), ("fortalecer", "fortalecer"),
 ("reforzar", "reforçar"), ("proteger", "proteger"), ("asegurar", "assegurar"), ("garantizar", "garantir"),
 ("consolidar", "consolidar"), ("estabilizar", "estabilizar"), ("solidificar", "solidificar"),
 ("unificar", "unificar"), ("integrar", "integrar"), ("conectar", "conectar"), ("relacionar", "relacionar"),
 ("asociar", "associar"), ("enlazar", "ligar"), ("combinar", "combinar"), ("mezclar", "misturar"),
 ("juntar", "juntar"), ("agrupar", "agrupar"), ("acompañar", "acompanhar"), ("sustentar", "sustentar"),
 ("respaldar", "apoiar"), ("apoyar", "apoiar"), ("asegurar", "assegurar"), ("reafirmar", "reafirmar"),
 ("confirmar", "confirmar"), ("ratificar", "ratificar"), ("avalizar", "avaliar"), ("validar", "validar"),
 ("certificar", "certificar"), ("reconocer", "reconhecer"), ("aceptar", "aceitar"), ("admitir", "admitir"),
 ("aprobar", "aprovar"), ("firmar", "assinar"), ("suscribir", "assinar"), ("dar", "dar"),
 ("conceder", "conceder"), ("otorgar", "dar"), ("donar", "doar"), ("regalar", "dar de presente"),
 ("compartir", "compartilhar"), ("reunir", "reunir"), ("juntar", "juntar"), ("revisar", "rever"),
 ("verificar", "verificar"), ("analizar", "analisar"), ("estudiar", "estudar"), ("investigar", "investigar"),
 ("explorar", "explorar"), ("probar", "experimentar"), ("calibrar", "calibrar"), ("medir", "medir"),
 ("pesar", "pesar"), ("separar", "separar"), ("clasificar", "classificar"), ("etiquetar", "etiquetar"),
 ("organizar", "organizar"), ("preparar", "preparar"), ("guardar", "guardar"), ("archivar", "arquivar"),
 ("borrar", "deletar"), ("sacar", "tirar"), ("quitar", "remover"), ("colocar", "colocar"),
 ("despejar", "limpar"), ("limpiar", "limpar"), ("remover", "remover"), ("reemplazar", "substituir"),
 ("sustituir", "substituir"), ("actualizar", "atualizar"), ("refrescar", "atualizar"), ("renovar", "renovar"),
 ("cambiar", "trocar"), ("alterar", "alterar"), ("modificar", "modificar"), ("mejorar", "melhorar"),
 ("mejorar", "melhorar"), ("optimizar", "otimizar"), ("ajustar", "ajustar"), ("perfeccionar", "aperfeiçoar"),
 ("desarrollar", "desenvolver"), ("evolucionar", "evoluir"), ("crecer", "crescer"), ("expandir", "expandir"),
 ("aumentar", "aumentar"), ("ampliar", "ampliar"), ("incrementar", "aumentar"), ("fortalecer", "fortalecer"),
 ("reforzar", "reforçar"), ("proteger", "proteger"), ("asegurar", "assegurar"), ("garantizar", "garantir"),
 ("consolidar", "consolidar"), ("estabilizar", "estabilizar"), ("solidificar", "solidificar"),
 ("unificar", "unificar"), ("integrar", "integrar"), ("conectar", "conectar"), ("relacionar", "relacionar"),
 ("asociar", "associar"), ("enlazar", "ligar"), ("combinar", "combinar"), ("mezclar", "misturar"),
 ("juntar", "juntar"), ("agrupar", "agrupar"), ("acompañar", "acompanhar"), ("sustentar", "sustentar"),
 ("respaldar", "apoiar"), ("apoyar", "apoiar"), ("asegurar", "assegurar"), ("reafirmar", "reafirmar"),
 ("confirmar", "confirmar"), ("ratificar", "ratificar"), ("avalizar", "avaliar"), ("validar", "validar"),
 ("certificar", "certificar"), ("reconocer", "reconhecer"), ("aceptar", "aceitar"), ("admitir", "admitir"),
 ("aprobar", "aprovar"), ("firmar", "assinar"), ("suscribir", "assinar"), ("dar", "dar"),
 ("conceder", "conceder"), ("otorgar", "dar"), ("donar", "doar"), ("regalar", "dar de presente"),
 ("compartir", "compartilhar"), ("reunir", "reunir"), ("juntar", "juntar"), ("revisar", "rever"),
 ("verificar", "verificar"), ("analizar", "analisar"), ("estudiar", "estudar"), ("investigar", "investigar"),
 ("explorar", "explorar"), ("probar", "experimentar"), ("calibrar", "calibrar"), ("medir", "medir"),
 ("pesar", "pesar"), ("separar", "separar"), ("clasificar", "classificar"), ("etiquetar", "etiquetar"),
 ("organizar", "organizar"), ("preparar", "preparar"), ("guardar", "guardar"), ("archivar", "arquivar"),
 ("borrar", "deletar"), ("sacar", "tirar"), ("quitar", "remover"), ("colocar", "colocar"),
 ("despejar", "limpar"), ("limpiar", "limpar"), ("remover", "remover"), ("reemplazar", "substituir"),
 ("sustituir", "substituir"), ("actualizar", "atualizar"), ("refrescar", "atualizar"), ("renovar", "renovar"),
 ("cambiar", "trocar"), ("alterar", "alterar"), ("modificar", "modificar"), ("mejorar", "melhorar"),
 ("mejorar", "melhorar"), ("optimizar", "otimizar"), ("ajustar", "ajustar"), ("perfeccionar", "aperfeiçoar"),
 ("desarrollar", "desenvolver"), ("evolucionar", "evoluir"), ("crecer", "crescer"), ("expandir", "expandir"),
 ("aumentar", "aumentar"), ("ampliar", "ampliar"), ("incrementar", "aumentar"), ("fortalecer", "fortalecer"),
 ("reforzar", "reforçar"), ("proteger", "proteger"), ("asegurar", "assegurar"), ("garantizar", "garantir"),
 ("consolidar", "consolidar"), ("estabilizar", "estabilizar"), ("solidificar", "solidificar"),
 ("unificar", "unificar"), ("integrar", "integrar"), ("conectar", "conectar"), ("relacionar", "relacionar"),
 ("asociar", "associar"), ("enlazar", "ligar"), ("combinar", "combinar"), ("mezclar", "misturar"),
 ("juntar", "juntar"), ("agrupar", "agrupar"), ("acompañar", "acompanhar"), ("sustentar", "sustentar"),
 ("respaldar", "apoiar"), ("apoyar", "apoiar"), ("asegurar", "assegurar"), ("reafirmar", "reafirmar"),
 ("confirmar", "confirmar"), ("ratificar", "ratificar"), ("avalizar", "avaliar"), ("validar", "validar"),
 ("certificar", "certificar"), ("reconocer", "reconhecer"), ("aceptar", "aceitar"), ("admitir", "admitir"),
 ("aprobar", "aprovar"), ("firmar", "assinar"), ("suscribir", "assinar"), ("dar", "dar"),
 ("conceder", "conceder"), ("otorgar", "dar"), ("donar", "doar"), ("regalar", "dar de presente"),
 ("compartir", "compartilhar"), ("reunir", "reunir"), ("juntar", "juntar"), ("revisar", "rever"),
 ("verificar", "verificar"), ("analizar", "analisar"), ("estudiar", "estudar"), ("investigar", "investigar"),
 ("explorar", "explorar"), ("probar", "experimentar"), ("calibrar", "calibrar"), ("medir", "medir"),
 ("pesar", "pesar"), ("separar", "separar"), ("clasificar", "classificar"), ("etiquetar", "etiquetar"),
 ("organizar", "organizar"), ("preparar", "preparar"), ("guardar", "guardar"), ("archivar", "arquivar"),
 ("borrar", "deletar"), ("sacar", "tirar"), ("quitar", "remover"), ("colocar", "colocar"),
 ("despejar", "limpar"), ("limpiar", "limpar"), ("remover", "remover"), ("reemplazar", "substituir"),
 ("sustituir", "substituir"), ("actualizar", "atualizar"), ("refrescar", "atualizar"), ("renovar", "renovar"),
 ("cambiar", "trocar"), ("alterar", "alterar"), ("modificar", "modificar"), ("mejorar", "melhorar"),
 ("mejorar", "melhorar"), ("optimizar", "otimizar"), ("ajustar", "ajustar"), ("perfeccionar", "aperfeiçoar"),
 ("desarrollar", "desenvolver"), ("evolucionar", "evoluir"), ("crecer", "crescer"), ("expandir", "expandir"),
 ("aumentar", "aumentar"), ("ampliar", "ampliar"), ("incrementar", "aumentar"), ("fortalecer", "fortalecer"),
 ("reforzar", "reforçar"), ("proteger", "proteger"), ("asegurar", "assegurar"), ("garantizar", "garantir"),
 ("consolidar", "consolidar"), ("estabilizar", "estabilizar"), ("solidificar", "solidificar"),
 ("unificar", "unificar"), ("integrar", "integrar"), ("conectar", "conectar"), ("relacionar", "relacionar"),
 ("asociar", "associar"), ("enlazar", "ligar"), ("combinar", "combinar"), ("mezclar", "misturar"),
 ("juntar", "juntar"), ("agrupar", "agrupar"), ("acompañar", "acompanhar"), ("sustentar", "sustentar"),
 ("respaldar", "apoiar"), ("apoyar", "apoiar"), ("asegurar", "assegurar"), ("reafirmar", "reafirmar"),
 ("confirmar", "confirmar"), ("ratificar", "ratificar"), ("avalizar", "avaliar"), ("validar", "validar"),
 ("certificar", "certificar"), ("reconocer", "reconhecer"), ("aceptar", "aceitar"), ("admitir", "admitir"),
 ("aprobar", "aprovar"), ("firmar", "assinar"), ("suscribir", "assinar"), ("dar", "dar"),
 ("conceder", "conceder"), ("otorgar", "dar"), ("donar", "doar"), ("regalar", "dar de presente"),
 ("compartir", "compartilhar"), ("reunir", "reunir"), ("juntar", "juntar"), ("revisar", "rever"),
 ("verificar", "verificar"), ("analizar", "analisar"), ("estudiar", "estudar"), ("investigar", "investigar"),
 ("explorar", "explorar"), ("probar", "experimentar"), ("calibrar", "calibrar"), ("medir", "medir"),
 ("pesar", "pesar"), ("separar", "separar"), ("clasificar", "classificar"), ("etiquetar", "etiquetar"),
 ("organizar", "organizar"), ("preparar", "preparar"), ("guardar", "guardar"), ("archivar", "arquivar"),
 ("borrar", "deletar"), ("sacar", "tirar"), ("quitar", "remover"), ("colocar", "colocar"),
 ("despejar", "limpar"), ("limpiar", "limpar"), ("remover", "remover"), ("reemplazar", "substituir"),
 ("sustituir", "substituir"), ("actualizar", "atualizar"), ("refrescar", "atualizar"), ("renovar", "renovar"),
 ("cambiar", "trocar"), ("alterar", "alterar"), ("modificar", "modificar"), ("mejorar", "melhorar"),
 ("mejorar", "melhorar"), ("optimizar", "otimizar"), ("ajustar", "ajustar"), ("perfeccionar", "aperfeiçoar"),
 ("desarrollar", "desenvolver"), ("evolucionar", "evoluir"), ("crecer", "crescer"), ("expandir", "expandir"),
 ("aumentar", "aumentar"), ("ampliar", "ampliar"), ("incrementar", "aumentar"), ("fortalecer", "fortalecer"),
 ("reforzar", "reforçar"), ("proteger", "proteger"), ("asegurar", "assegurar"), ("garantizar", "garantir"),
 ("consolidar", "consolidar"), ("estabilizar", "estabilizar"), ("solidificar", "solidificar"),
 ("unificar", "unificar"), ("integrar", "integrar"), ("conectar", "conectar"), ("relacionar", "relacionar"),
 ("asociar", "associar"), ("enlazar", "ligar"), ("combinar", "combinar"), ("mezclar", "misturar"),
 ("juntar", "juntar"), ("agrupar", "agrupar"), ("acompañar", "acompanhar"), ("sustentar", "sustentar"),
 ("respaldar", "apoiar"), ("apoyar", "apoiar"), ("asegurar", "assegurar"), ("reafirmar", "reafirmar"),
 ("confirmar", "confirmar"), ("ratificar", "ratificar"), ("avalizar", "avaliar"), ("validar", "validar"),
 ("certificar", "certificar"), ("reconocer", "reconhecer"), ("aceptar", "aceitar"), ("admitir", "admitir"),
 ("aprobar", "aprovar"), ("firmar", "assinar"), ("suscribir", "assinar"),("caminar", "andar"), ("camina", "anda"), ("caminó", "andou"), ("caminando", "andando"),
 ("correr", "correr"), ("corre", "corre"), ("corrió", "correu"), ("corriendo", "correndo"),
 ("comer", "comer"), ("come", "come"), ("comió", "comeu"), ("comiendo", "comendo"),
 ("leer", "ler"), ("lee", "lê"), ("leyó", "leu"), ("leyendo", "lendo"),
 ("escribir", "escrever"), ("escribe", "escreve"), ("escribió", "escreveu"), ("escribiendo", "escrevendo")]

frenchDict  = Map.fromList [
    ("au revoir", "adeus"), ("s'il vous plaît", "por favor"), ("merci", "obrigado"), ("désolé", "desculpe")
    , ("je", "eu"), ("tu", "você"), ("il", "ele"), ("elle", "ela"), ("cela", "isso"), ("nous", "nós"), ("ils", "eles")
    , ("mon", "meu"), ("ton", "seu"), ("son", "dele"), ("sa", "dela"), ("ses", "seu"), ("notre", "nosso"), ("leur", "deles")
    , ("ce", "este"), ("cela", "aquele"), ("ces", "estes"), ("ceux", "aqueles"),
 ("marcher", "andar"), ("marche", "anda"), ("marchait", "andou"), ("marchant", "andando"),
 ("courir", "correr"), ("court", "corre"), ("courait", "correu"), ("courant", "correndo"),
 ("manger", "comer"), ("mange", "come"), ("mangeait", "comeu"), ("mangeant", "comendo"),
 ("lire", "ler"), ("lit", "lê"), ("lisait", "leu"), ("lisant", "lendo"),
 ("écrire", "escrever"), ("écrit", "escreve"), ("écrivait", "escreveu"), ("écrivant", "escrevendo"),
 ("bonjour", "olá"), ("monde", "mundo"), ("comment", "como"), ("ça", "está"), ("vous", "você"),
 ("au revoir", "adeus"), ("s'il vous plaît", "por favor"), ("merci", "obrigado"), ("désolé", "desculpe"),
 ("oui", "sim"), ("non", "não"), ("peut-être", "talvez"), ("toujours", "sempre"), ("jamais", "nunca"),
 ("quelquefois", "às vezes"), ("souvent", "frequentemente"), ("rarement", "raramente"), ("tous les jours", "todos os dias"),
 ("tout le monde", "todo mundo"), ("personne", "ninguém"), ("quelqu'un", "alguém"), ("beaucoup", "muitos"),
 ("peu", "pouco"), ("tout", "tudo"), ("rien", "nada"), ("chaque", "cada"), ("aucun", "nenhum"), ("tout le monde", "todo mundo"), ("certain", "certo"), ("certaine", "certa"), ("quelque", "algum"),
 ("toute", "toda"), ("tous", "todos"), ("et", "e"), ("ou", "ou"), ("mais", "mas"), ("parce que", "porque"), ("donc", "portanto"),
 ("bien", "bem"), ("mal", "mal"), ("très", "muito"), ("assez", "bastante"), ("trop", "demais"), ("moins", "menos"),
 ("plus", "mais"), ("ici", "aqui"), ("là", "lá"), ("où", "onde"), ("quand", "quando"), ("pourquoi", "por que"), ("quoi", "o que"),
 ("qui", "quem"), ("combien", "quanto"), ("quel", "qual"), ("par", "por"), ("avec", "com"),
 ("sans", "sem"),
 ("dans", "dentro"),
 ("sur", "sobre"),
 ("sous", "debaixo"),
 ("devant", "na frente"),
 ("derrière", "atrás"),
 ("avant", "antes"),
 ("après", "depois"),
 ("pendant", "durante"),
 ("à", "a"),
 ("de", "de"),
 ("en", "em"),
 ("pour", "para"),
 ("parmi", "entre"),
 ("entre", "entre"),
 ("selon", "segundo"),
 ("malgré", "apesar de"),
 ("à cause de", "por causa de"),
 ("grâce à", "graças a"),
 ("à propos de", "a respeito de"),
 ("entre autres", "entre outros"),
 ("avant tout", "antes de tudo"),
 ("comme", "como"),
 ("si", "se"),
 ("lorsque", "quando"),
 ("tandis que", "enquanto"),
 ("bien que", "embora"),
 ("par contre", "por outro lado"),
 ("au contraire", "pelo contrário"),
 ("même si", "mesmo que"),
 ("alors", "então"),
 ("ainsi", "assim"),
 ("ensuite", "depois"),
 ("puis", "então"),
 ("d'abord", "primeiro"),
 ("finalement", "finalmente"),
 ("enfin", "finalmente"),
 ("parfois", "às vezes"),
 ("généralement", "geralmente"),
 ("d'habitude", "normalmente"),
 ("souvent", "frequentemente"),
 ("rarement", "raramente"),
 ("normalement", "normalmente"),
 ("comme d'habitude", "como de costume"),
 ("surtout", "sobretudo"),
 ("tout d'abord", "em primeiro lugar"),
 ("c'est-à-dire", "ou seja"),
 ("en effet", "de fato"),
 ("par exemple", "por exemplo"),
 ("en résumé", "em resumo"),
 ("en conclusion", "em conclusão"),
 ("en revanche", "em contrapartida"),
 ("autrement dit", "em outras palavras"),
 ("en gros", "em suma"),
 ("en somme", "em suma"),
 ("voilà", "aqui está"),
 ("finalement", "finalmente"),
 ("d'accord", "de acordo"),
 ("c'est ça", "é isso"),
 ("vraiment", "realmente"),
 ("probablement", "provavelmente"),
 ("évidemment", "evidentemente"),
 ("sûrement", "certamente"),
 ("absolument", "absolutamente"),
 ("exactement", "exatamente"),
 ("précisément", "precisamente"),
 ("particulièrement", "particularmente"),
 ("certainement", "certamente"),
 ("aussi", "também"),
 ("trop", "demais"),
 ("moins", "menos"),
 ("plus", "mais"),
 ("l'autre", "o outro"),
 ("l'un", "um"),
 ("l'une", "uma"),
 ("moi", "eu"),
 ("toi", "tu"),
 ("lui", "ele"),
 ("elle", "ela"),
 ("nous", "nós"),
 ("vous", "vocês"),
 ("eux", "eles"),
 ("elles", "elas"),
 ("quelqu'un", "alguém"),
 ("personne", "ninguém"),
 ("rien", "nada"),
 ("tout", "tudo"),
 ("beaucoup de", "muitos"),
 ("peu de", "poucos"),
 ("certaines", "algumas"),
 ("tous les", "todos os"),
 ("chaque", "cada"),
 ("quelques", "alguns"),
 ("nul", "nenhum"),
 ("quelque chose", "algo"),
 ("aucune", "nenhuma"),
 ("certains", "alguns"),
 ("parfois", "às vezes"),
 ("toujours", "sempre"),
 ("tous", "todos"),
 ("tout", "tudo"),
 ("rien", "nada"),
 ("certaines", "algumas"),
 ("tous les", "todos os"),
 ("qui que ce soit", "quem quer que seja"),
 ("quoi que ce soit", "o que quer que seja"),
 ("où que ce soit", "onde quer que seja"),
 ("quand que ce soit", "quando quer que seja"),
 ("comment que ce soit", "como quer que seja"),
 ("où", "onde"),
 ("quand", "quando"),
 ("quoi", "o que"),
 ("qui", "quem"),
 ("pourquoi", "por que"),
 ("comment", "como"),
 ("combien", "quanto"),
 ("quel", "qual"),
 ("quelque chose", "algo"),
 ("tout", "tudo"),
 ("rien", "nada"),
 ("un", "um"),
 ("une", "uma"),
 ("deux", "dois"),
 ("trois", "três"),
 ("quatre", "quatro"),
 ("cinq", "cinco"),
 ("six", "seis"),
 ("sept", "sete"),
 ("huit", "oito"),
 ("neuf", "nove"),
 ("dix", "dez"),
 ("premier", "primeiro"),
 ("deuxième", "segundo"),
 ("troisième", "terceiro"),
 ("quatrième", "quarto"),
 ("cinquième", "quinto"),
 ("sixième", "sexto"),
 ("septième", "sétimo"),
 ("huitième", "oitavo"),
 ("neuvième", "nono"),
 ("dixième", "décimo"),
 ("dernier", "último"),
 ("avant-dernier", "penúltimo")]